### ISSUE TITLE
Future of the old accesslint.com check?

### ISSUE THREAD

**Issue by j9t** [AccessLint/www.accesslint.com#12]
Perhaps not the best spot to ask this but are there any plans to reinstate the old check that was available on accesslint.com? It was really useful—and really important, too, as we face an increasing shortage of readily available accessibility tools.

(I run [uitest.com](https://uitest.com/) and had accesslint.com linked as one of the [accessibility resources](https://uitest.com/en/analysis/). I’d be more than happy to link back if there was some direct access to the tool again.)

**Comment by tysongach** [comment]
Hi @j9t!

I believe you’re talking about Accesslint::Ci, which was found at accesslint.com until a couple weeks ago. At this time, we have deprecated that iteration of AccessLint and don’t have plans to work on it again. But you can find the project here: https://github.com/AccessLint/accesslint-ci

You may also want to check out aXe, which Accesslint::CI ran under the hood: https://github.com/dequelabs/axe-core

We found some value in the CI version of AccessLint, but setup was a burden and it was only available with CircleCI, which not everyone uses. The new version of AccessLint makes setup a breeze, it isn't tied to CI or any CI vendor and it still brings accessibility review right into Pull Requests, which we think can be a powerful educational tool while also be helpful for catches errors.

While it’s testing footprint is a bit smaller, we hope this focus and new direction gives us a stronger foundation to iterate on.

Have you had a chance to use the AccessLint GitHub app yet? We’d love to keep the conversation going to hear about the pros and cons between the old and new AccessLint.

**Comment by j9t** [comment]
Yes, I was talking about Accesslint::Ci :)

Unfortunate! I’m excited to see AccessLint and try it here on GitHub (I hooked it up to my repositiories), but I’ve found the CI version more readily… accessible—and also easier to promote.

Thanks for clarifying, then; I’m looking forward to seeing what’s next!

**Comment by tysongach** [comment]
Gotcha! Let us know what you think!

I'm going to close this for now, as it's non-actionable. But feel free to ping us anytime. You can also join our public Slack and chat with us there: http://slack.accesslint.com/
