### ISSUE TITLE
Add RSS feed to Blogs

### ISSUE THREAD

**Issue by nschonni** [AccessLint/www.accesslint.com#5]
Note sure what is available with the current setup, but something like that Jekyll RSS plug-in that automatically creates the feed file would be good.

**Comment by tysongach** [comment]
That’s a great idea! We are running the site on Middleman and I believe we can use builder to create a feed.

**Comment by tysongach** [comment]
@nschonni We now have a feed at https://www.accesslint.com/blog/feed.xml

Thanks for the idea!
